version: '3'

services:
  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  front:
    image: matoba/ssldevenv
    ports:
      - "443:443"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  selenium:
    image: selenium/standalone-chrome:3.4
    ports:
      - "4444:4444"