version: '3'

services:
  dockerappwithci:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  ssldevenv:
    image: matoba/ssldevenv
    links:
      - dockerappwithci:webapp
    ports:
      - "443:443"